zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    core-service:
      path: /core/**
#      url: http://localhost:8071
      serviceId: CORE-SERVICE
    merchant-service:
      path: /merchant/**
      serviceId: MERCHANT-SERVICE
    psp-service:
          path: /psp/**
          serviceId: PSP-SERVICE

eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ - configured by Spring Cloud Config
  instance:
    hostname: localhost

server:
  port: 9000

spring:
  application:
    name: zuul-server

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
