spring:
  application:
    name: zuul-server

server:
  port: 8025

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  ignoredServices: '*'
  routes:
    core-service:
      path: /core/**
#      url: http://localhost:8071
      serviceId: CORE-SERVICE
    merchant-service:
      path: /merchant/**
      serviceId: MERCHANT-SERVICE
    psp-service:
      path: /psp/**
      serviceId: PSP-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000
