spring:
  application:
    name: core-service

server:
  port: 8890

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ - configured by Spring Cloud Config
  instance:
    hostname: localhost